[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[client]
showErrorDetails = false
toolbarMode = "minimal"

[theme]
base = "light"
primaryColor = "#00506b"
backgroundColor = "#F9F9F9"
secondaryBackgroundColor = "#B5E8F7"
textColor = "#111827"
font = "sans serif"
